### ISSUE TITLE
Write to an android HCE

### ISSUE THREAD

**Issue by sagar-patil-52** [underwindfall/NFCReaderiOS#1]
I need help for 2 task 
1 -  write/send command to an Android emulating card (or Android acting as an HCE). I have implemented sendCommand(apdu:completionHandler:) but I suspect, it will only work for NFCISO7816 tags. I couldn't test this though as I don't have the iso7816 tag.
2 - Could this (write/send command to HCE) be achieved through background i.e. without opening the app. I know the tags can be read from background.

**Comment by underwindfall** [comment]
@sagar-patil-52 about HCE, you should check [my repo](https://github.com/underwindfall/NFCAndroid), as for me HCE runs as background service more info you need to check [documentation](https://developer.android.com/guide/topics/connectivity/nfc/hce)

**Comment by iamporus** [comment]
I'm looking for an app for iOS which should interact with an Android HCE smartphone. I have already created an Android app based on HCE by referring to your [repo](https://github.com/underwindfall/NFCAndroid) and it works as expected when I tap another android device working as an NFC Reader. 

However, when I tap my iPhone with your NFC Reader app to the Android device, the scanning fails. Have you come across this problem? What am I missing?

**Comment by underwindfall** [comment]
@iamporus I need more details about failure.
 Such as
- what kind of log displayed when it failed.
- your account developer ios has activated nfc permission or not

**Comment by iamporus** [comment]
Sorry for replying so late. Apparently, there were not any issues with NFCReaderiOS implementation. 
You can go ahead and close the issue.
